<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-04-01T11:17:48+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.1.3',
    'version_db_installed' => '20220908074900',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1680347868,
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
];
