<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-04-01T11:16:59+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'db',
        ],
    ],
];
